version: "3"

services:
  rickandmortyapi:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: rickandmortyapi_app
    container_name: rickandmortyapi
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      BASE_URL: ${BASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}

  db:
    image: postgres:14.3
    container_name: rickandmortyapi_db
    restart: "always"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./.postgres:/var/lib/postgresql/data
