name: Get Random Characters
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0,12 * * *

jobs:
  characters:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm get-random-characters
      - run: |
          git config user.name iswilljr
          git config user.email iswilljr@gmail.com
          git add .
          git commit -m "feat: add new random characters"
          git push
