name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Rick and Morty API Unit and E2E Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Unit Testing
        run: pnpm run test
      - name: E2E Testing
        run: pnpm run test:e2e
  site_test:
    name: Rick and Morty API Site E2E Testing
    defaults:
      run:
        working-directory: site
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Site E2E Testing
        run: pnpm exec playwright test
